FROM debian:buster-slim

ADD sources.list /etc/apt/sources.list
# debian 9
#RUN apt-get update && apt-get -y install make cmake gcc gcc-6 libpcre3 libpcre3-dev openssl libssl-dev libperl-dev zlib1g-dev

# debian10
RUN apt-get update && apt-get -y install make cmake gcc gcc-7 libpcre3 libpcre3-dev openssl libssl-dev libperl-dev zlib1g-dev

