version: '3.4'
services:
     tracker:
      image: jacky90/fastdfs:6.01
      container_name: tracker  
      restart:
        always
      network_mode: "host"
      environment:
        SERVER: "tracker"
      volumes:
        - ./etc/fdfs:/etc/fdfs
        - ./data/fastdfs:/data/fastdfs
      ports:
          - "22122:22122"
      expose:
          - 22122

     storage:
      image: jacky90/fastdfs:6.01
      container_name: tracker-storage
      restart:
        always
      network_mode: "host"
      volumes:
        - ./etc/fdfs:/etc/fdfs
        - ./data/fastdfs:/data/fastdfs
      depends_on:
          - "tracker"
      ports:
          - "23000:23000"
          - "8888:8888"
      expose:
          - 23000
          - 8888
